version: '3.7'

services:
  database:
    image: mongo
    container_name: node-boilerplate-mongo
    restart: always
    ports:
      - "27017:27017" 
    networks:
      - private-network

  app:
    build: .
    image: node-boilerplate/node
    restart: always
    container_name: node-boilerplate-node
    environment:
      SERVER_PORT: 3000
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    networks:
      - private-network
    depends_on:
      - database

networks:
  private-network:
    name: private-network
    driver: bridge